---

- name: Provision all classifiers
  hosts: "{{server}}"
  connection: local
  gather_facts: false
  tasks:
      - netconf_config:
          host: "{{ansible_ssh_host}}"
          username: "{{netconf_uid}}"
          password: "{{netconf_pwd}}"
          port: 830
          hostkey_verify: False
          xml: {{ lookup('template', createClassifiers.j2') }}
