---

- name: Provision all classifiers
  hosts: "{{server}}"
  connection: local
  gather_facts: false
  tasks:
      - netconf_config:
          host: "{{ansible_ssh_host}}"
          username: "{{netconf_uid}}"
          password: "{{netconf_pwd}}"
          port: 830
          hostkey_verify: False
          xml:
                 <config>
                   <classifiers xmlns="urn:ciena:params:xml:ns:yang:ciena-pn::ciena-mef-classifier">
                     <classifier operation="merge">
                       <name>VLAN30</name>
                           <filter-entry>
                                <filter-parameter xmlns:classifier="urn:ciena:params:xml:ns:yang:ciena-pn::ciena-mef-classifier">classifier:vtag-stack</filter-parameter>
                                <vtags>
                                    <tag>1</tag>
                                    <vlan-id>30</vlan-id>
                                </vtags>
                           </filter-entry>
                     </classifier>
                   </classifiers>
                 </config>
