---

- name: Provision all classifiers
  hosts: "{{server}}"
  connection: local
  gather_facts: false
  tasks:
      - netconf_config:
          host: "{{ansible_ssh_host}}"
          username: "{{netconf_uid}}"
          password: "{{netconf_pwd}}"
          port: 830
          hostkey_verify: False
          xml:
                 <config>
                   <classifiers xmlns="urn:ciena:params:xml:ns:yang:ciena-pn::ciena-mef-classifier">
                     <classifier>
                       <name>{{wan_clsfr_name}}</name>
                       <filter-operation>match-all</filter-operation>
                       <filter-entry>
                        <filter-parameter>classifier:vtag-stack</filter-parameter>
            	            <vtags>
                            <tag>1</tag>
                            <vlan-id>{{wan_clsfr_vid}}</vlan-id>
                         </vtags>
                      </filter-entry>
                     </classifier>
                     <classifier>
                       <name>{{lan_clsfr_name}}</name>
                       <filter-operation>match-all</filter-operation>
                       <filter-entry>
                        <filter-parameter>classifier:vtag-stack</filter-parameter>
            	            <vtags>
                            <tag>1</tag>
                            <vlan-id>{{lan_clsfr_vid}}</vlan-id>
                         </vtags>
                      </filter-entry>
                     </classifier>
                   </classifiers>
                 </config>
