---

- name: Delete {{vnf_name}} VNF
  hosts: "{{server}}"
  connection: local
  gather_facts: false
  tasks:
      - netconf_config:
          host: "{{ansible_ssh_host}}"
          username: "{{netconf_uid}}"
          password: "{{netconf_pwd}}"
          port: 830
          hostkey_verify: False
          xml:
              <config>
                <sfs  xmlns="urn:ciena:params:xml:ns:yang:ciena-pn::ciena-sf">
                      <sf nc:operation="delete" xmlns:nc="urn:ietf:params:xml:ns:netconf:base:1.0">
                         <sf-name>{{vnf_name}}</sf-name>
                       </sf>
                  </sfs>
             </config>
