---

- name: testing Expect module
  hosts: "{{server}}"
  gather_facts: False
  connection: local
  tasks:
      - name: Test with Touch
        expect:
            echo: True
            command: sudo virsh console Fortinet
            responses: 
                (?i)Escape character is ^]: /r
                (?i)login: admin
                (?i)password: /r
                (?i)#: execute reboot
                (y/n): y
                
