---

- name: Start {{vnf_name}} VNF
  hosts: "{{server}}"
  connection: local
  gather_facts: false
  tasks:
      - netconf_config:
          host: "{{ansible_ssh_host}}"
          username: "{{netconf_uid}}"
          password: "{{netconf_pwd}}"
          port: 830
          hostkey_verify: False
          xml:
             <config>
              <sfs xmlns="urn:ciena:params:xml:ns:yang:ciena-pn::ciena-sf">
               <sf>
                <sf-name>{{vnf_name}}</sf-name>
                  <sf-operation>
                       <state>start</state>
                  </sf-operation>
               </sf>
              </sfs>
             </config>
